-- =============================================================================
-- Coopvest Africa — Supabase schema
--
-- This file is the source of truth for the Postgres schema backing the mobile
-- app and the admin web dashboard. Apply it to the Supabase project defined by
-- SUPABASE_URL. All member data flows through these tables; the admin web
-- portal (see Admin-Dashboard repo) reads them through the mobile backend's
-- HTTP API with a service-role token — admins do not connect to Postgres
-- directly.
--
-- Conventions:
--   * Primary keys are UUIDs generated by gen_random_uuid().
--   * Foreign keys to the authenticated user use `profile_id UUID
--     REFERENCES public.profiles(id) ON DELETE CASCADE`.
--   * Monetary amounts use DECIMAL(18,2).
--   * All tables carry created_at / updated_at TIMESTAMPTZ with defaults.
--   * Row Level Security (RLS) is enabled on every public table; members can
--     only read/write their own rows, and the service role bypasses RLS for
--     admin operations.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Core profile (extends supabase auth.users)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  name TEXT,
  role TEXT DEFAULT 'member' CHECK (role IN ('member', 'admin', 'superadmin', 'staff')),
  is_active BOOLEAN DEFAULT true,
  is_flagged BOOLEAN DEFAULT false,
  flagged_reason TEXT,
  kyc_verified BOOLEAN DEFAULT false,
  organization_id UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS access_level TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_password_change_at TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS firebase_uid TEXT UNIQUE;

CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_department ON public.profiles(department);

-- -----------------------------------------------------------------------------
-- KYC
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.kyc (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_review', 'verified', 'rejected', 'expired')),
  verified BOOLEAN DEFAULT false,
  verified_at TIMESTAMPTZ,
  verification_level INT DEFAULT 0,
  rejection_reason TEXT,
  national_id TEXT,
  address TEXT,
  date_of_birth DATE,
  personal_info JSONB DEFAULT '{}'::jsonb,
  contact_info JSONB DEFAULT '{}'::jsonb,
  employment JSONB DEFAULT '{}'::jsonb,
  bank_info JSONB DEFAULT '{}'::jsonb,
  selfie JSONB DEFAULT '{}'::jsonb,
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.kyc_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kyc_id UUID REFERENCES public.kyc(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('national_id', 'passport', 'drivers_license', 'voters_card', 'utility_bill', 'bank_statement')),
  document_number TEXT,
  expiry_date DATE,
  front_image_url TEXT,
  back_image_url TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected', 'expired')),
  rejection_reason TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  verified_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_kyc_documents_profile ON public.kyc_documents(profile_id);

-- -----------------------------------------------------------------------------
-- Savings (aggregate) + individual savings goals
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.savings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  total_saved DECIMAL(18, 2) DEFAULT 0,
  monthly_savings DECIMAL(18, 2) DEFAULT 0,
  first_savings_date TIMESTAMPTZ,
  consecutive_months INTEGER DEFAULT 0,
  last_savings_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.savings_goals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  target_amount DECIMAL(18, 2) NOT NULL,
  current_amount DECIMAL(18, 2) DEFAULT 0,
  target_date DATE,
  frequency TEXT CHECK (frequency IN ('daily', 'weekly', 'biweekly', 'monthly')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused', 'cancelled')),
  auto_debit BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_savings_goals_profile ON public.savings_goals(profile_id);

-- -----------------------------------------------------------------------------
-- Referrals
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.referrals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  my_referral_code TEXT UNIQUE,
  referred_by_id UUID REFERENCES public.profiles(id),
  referred_by_code TEXT,
  referral_count INTEGER DEFAULT 0,
  confirmed_referral_count INTEGER DEFAULT 0,
  current_tier_bonus DECIMAL(5, 2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Each referral relationship event (one row per referred user)
CREATE TABLE IF NOT EXISTS public.referral_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referral_id TEXT UNIQUE NOT NULL,
  referrer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  referrer_name TEXT,
  referred_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  referred_name TEXT,
  referral_code TEXT NOT NULL,
  confirmed BOOLEAN DEFAULT false,
  confirmed_at TIMESTAMPTZ,
  is_flagged BOOLEAN DEFAULT false,
  flagged_reason TEXT,
  flagged_at TIMESTAMPTZ,
  bonus_consumed BOOLEAN DEFAULT false,
  consumed_at TIMESTAMPTZ,
  tier_bonus_percent DECIMAL(5, 2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_referral_events_referrer ON public.referral_events(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referral_events_confirmed ON public.referral_events(confirmed);
CREATE INDEX IF NOT EXISTS idx_referral_events_flagged ON public.referral_events(is_flagged);

-- -----------------------------------------------------------------------------
-- Wallet + transactions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wallets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'NGN',
  is_active BOOLEAN DEFAULT true,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id TEXT UNIQUE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  wallet_id UUID REFERENCES public.wallets(id) ON DELETE SET NULL,
  type TEXT NOT NULL CHECK (type IN (
    'deposit','withdrawal','transfer_in','transfer_out','investment',
    'investment_return','savings_deposit','savings_withdrawal',
    'loan_disbursement','loan_repayment','referral_bonus','interest',
    'fee','refund','adjustment','rollover'
  )),
  category TEXT CHECK (category IN ('credit', 'debit')),
  amount DECIMAL(18, 2) NOT NULL,
  currency TEXT DEFAULT 'NGN',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed','cancelled','reversed')),
  payment_method TEXT DEFAULT 'wallet',
  description TEXT NOT NULL,
  reference TEXT,
  loan_id UUID,
  savings_goal_id UUID,
  investment_pool_id UUID,
  bank_account_id UUID,
  gateway JSONB DEFAULT '{}'::jsonb,
  fees JSONB DEFAULT '{}'::jsonb,
  metadata JSONB DEFAULT '{}'::jsonb,
  net_amount DECIMAL(18, 2),
  balance_before DECIMAL(18, 2),
  balance_after DECIMAL(18, 2),
  failure_reason TEXT,
  reversed BOOLEAN DEFAULT false,
  reversed_at TIMESTAMPTZ,
  initiated_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transactions_profile ON public.transactions(profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON public.transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON public.transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_reference ON public.transactions(reference);

-- -----------------------------------------------------------------------------
-- Bank accounts
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bank_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  bank_name TEXT NOT NULL,
  bank_code TEXT,
  account_number TEXT NOT NULL,
  account_name TEXT NOT NULL,
  account_type TEXT CHECK (account_type IN ('savings', 'current')),
  is_primary BOOLEAN DEFAULT false,
  is_verified BOOLEAN DEFAULT false,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bank_accounts_profile ON public.bank_accounts(profile_id);

-- -----------------------------------------------------------------------------
-- Loans + guarantor QR codes
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id TEXT UNIQUE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  loan_type TEXT NOT NULL CHECK (loan_type IN ('Quick Loan', 'Micro Loan', 'Business Loan', 'Emergency Loan')),
  amount DECIMAL(18, 2) NOT NULL,
  tenure_months INTEGER NOT NULL,
  purpose TEXT NOT NULL,
  base_interest_rate DECIMAL(6, 3) NOT NULL,
  referral_bonus_percent DECIMAL(6, 3) DEFAULT 0,
  effective_interest_rate DECIMAL(6, 3) NOT NULL,
  monthly_repayment DECIMAL(18, 2) NOT NULL,
  total_repayment DECIMAL(18, 2) NOT NULL,
  savings_from_bonus DECIMAL(18, 2) DEFAULT 0,
  remaining_balance DECIMAL(18, 2),
  remaining_months INTEGER,
  next_due_date DATE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'active', 'rejected', 'completed', 'defaulted')),
  approved_by UUID REFERENCES public.profiles(id),
  approved_at TIMESTAMPTZ,
  rejected_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loans_profile ON public.loans(profile_id);
CREATE INDEX IF NOT EXISTS idx_loans_status ON public.loans(status);

CREATE TABLE IF NOT EXISTS public.loan_qrs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qr_id TEXT UNIQUE NOT NULL,
  loan_id UUID REFERENCES public.loans(id) ON DELETE CASCADE,
  applicant_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  applicant_name TEXT,
  applicant_phone TEXT,
  loan_amount DECIMAL(18, 2),
  loan_currency TEXT DEFAULT 'NGN',
  loan_tenure INTEGER,
  interest_rate DECIMAL(6, 3),
  monthly_repayment DECIMAL(18, 2),
  total_repayment DECIMAL(18, 2),
  purpose TEXT,
  qr_data JSONB,
  qr_code TEXT,
  signature TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'expired', 'invalidated')),
  scan_count INTEGER DEFAULT 0,
  guarantors_found INTEGER DEFAULT 0,
  guarantors_required INTEGER DEFAULT 3,
  scans JSONB DEFAULT '[]'::jsonb,
  expires_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loan_qrs_loan ON public.loan_qrs(loan_id);
CREATE INDEX IF NOT EXISTS idx_loan_qrs_applicant ON public.loan_qrs(applicant_id);

CREATE TABLE IF NOT EXISTS public.loan_guarantors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id UUID REFERENCES public.loans(id) ON DELETE CASCADE,
  qr_id UUID REFERENCES public.loan_qrs(id) ON DELETE SET NULL,
  guarantor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'consented', 'rejected', 'revoked')),
  consented_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(loan_id, guarantor_id)
);

-- -----------------------------------------------------------------------------
-- Rollovers (loan extension requests)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.rollovers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rollover_id TEXT UNIQUE NOT NULL,
  loan_id UUID REFERENCES public.loans(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  original_loan JSONB DEFAULT '{}'::jsonb,
  requested_tenure INTEGER NOT NULL,
  requested_reason TEXT DEFAULT '',
  new_terms JSONB DEFAULT '{}'::jsonb,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'completed')),
  reviewed_by UUID REFERENCES public.profiles(id),
  reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rollovers_profile ON public.rollovers(profile_id);
CREATE INDEX IF NOT EXISTS idx_rollovers_loan ON public.rollovers(loan_id);

-- -----------------------------------------------------------------------------
-- Investment pools + participations
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.investment_pools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pool_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  target_amount DECIMAL(18, 2) NOT NULL,
  raised_amount DECIMAL(18, 2) DEFAULT 0,
  expected_return_percent DECIMAL(6, 3),
  duration_months INTEGER,
  risk_level TEXT CHECK (risk_level IN ('low', 'medium', 'high')),
  status TEXT DEFAULT 'open' CHECK (status IN ('draft', 'open', 'funded', 'active', 'completed', 'cancelled')),
  opens_at TIMESTAMPTZ,
  closes_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.investment_participations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pool_id UUID REFERENCES public.investment_pools(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount DECIMAL(18, 2) NOT NULL,
  expected_return DECIMAL(18, 2),
  actual_return DECIMAL(18, 2),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'matured', 'withdrawn', 'refunded')),
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  matured_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_investment_participations_profile ON public.investment_participations(profile_id);
CREATE INDEX IF NOT EXISTS idx_investment_participations_pool ON public.investment_participations(pool_id);

-- -----------------------------------------------------------------------------
-- Notifications
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('transaction','savings','investment','loan','referral','kyc','system','promotion','security','reminder')),
  category TEXT DEFAULT 'info' CHECK (category IN ('credit','debit','milestone','expiry','status_change','info','warning','success','action_required')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  data JSONB DEFAULT '{}'::jsonb,
  reference_model TEXT,
  reference_id UUID,
  priority TEXT DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMPTZ,
  is_archived BOOLEAN DEFAULT false,
  archived_at TIMESTAMPTZ,
  is_pushed BOOLEAN DEFAULT false,
  pushed_at TIMESTAMPTZ,
  action_url TEXT,
  action_label TEXT,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_profile ON public.notifications(profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications(profile_id, is_read, is_archived);
CREATE INDEX IF NOT EXISTS idx_notifications_priority ON public.notifications(priority);

-- -----------------------------------------------------------------------------
-- Support tickets
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id TEXT UNIQUE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('loan_issue','guarantor_consent','referral_bonus','repayment_issue','account_kyc','technical_bug','other')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
  status TEXT DEFAULT 'open' CHECK (status IN ('open','in_progress','awaiting_user','resolved','closed')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  related_reference JSONB DEFAULT '{}'::jsonb,
  assigned_staff_id UUID REFERENCES public.profiles(id),
  resolution TEXT,
  resolved_at TIMESTAMPTZ,
  resolved_by UUID REFERENCES public.profiles(id),
  last_user_response_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}'::jsonb,
  abuse_flags JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickets_profile ON public.tickets(profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_category ON public.tickets(category);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned ON public.tickets(assigned_staff_id);

CREATE TABLE IF NOT EXISTS public.ticket_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES public.tickets(id) ON DELETE CASCADE,
  author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  author_role TEXT CHECK (author_role IN ('member','staff','system')),
  body TEXT NOT NULL,
  is_internal BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket ON public.ticket_messages(ticket_id, created_at);

CREATE TABLE IF NOT EXISTS public.ticket_attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES public.tickets(id) ON DELETE CASCADE,
  message_id UUID REFERENCES public.ticket_messages(id) ON DELETE SET NULL,
  uploaded_by UUID REFERENCES public.profiles(id),
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_size INTEGER,
  mime_type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ticket_status_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES public.tickets(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  changed_by UUID REFERENCES public.profiles(id),
  note TEXT,
  changed_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Audit logs
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_role TEXT,
  action TEXT NOT NULL,
  target_model TEXT,
  target_id TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON public.audit_logs(actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON public.audit_logs(created_at DESC);

-- -----------------------------------------------------------------------------
-- Settings (user + system-wide)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_settings (
  profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  preferences JSONB DEFAULT '{}'::jsonb,
  notifications JSONB DEFAULT '{"email": true, "push": true, "sms": false}'::jsonb,
  security JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.system_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  description TEXT,
  updated_by UUID REFERENCES public.profiles(id),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Watchlist
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.watchlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL CHECK (item_type IN ('pool', 'member', 'loan', 'other')),
  item_id TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(profile_id, item_type, item_id)
);

CREATE INDEX IF NOT EXISTS idx_watchlist_profile ON public.watchlist(profile_id);

-- -----------------------------------------------------------------------------
-- Loan repayments (every installment a member pays back)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loan_repayments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_id UUID REFERENCES public.loans(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount DECIMAL(18, 2) NOT NULL,
  principal_component DECIMAL(18, 2),
  interest_component DECIMAL(18, 2),
  due_date DATE,
  paid_at TIMESTAMPTZ,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'overdue', 'waived', 'restructured')),
  reference TEXT,
  recorded_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loan_repayments_loan ON public.loan_repayments(loan_id);
CREATE INDEX IF NOT EXISTS idx_loan_repayments_status ON public.loan_repayments(status);

-- -----------------------------------------------------------------------------
-- Scheduled notifications (queued for a future send time)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.scheduled_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT DEFAULT 'announcement',
  category TEXT DEFAULT 'info',
  priority TEXT DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  audience TEXT NOT NULL DEFAULT 'all' CHECK (audience IN ('all', 'active', 'specific')),
  target_profile_ids UUID[],
  channels TEXT[] DEFAULT ARRAY['in_app']::TEXT[],
  scheduled_for TIMESTAMPTZ NOT NULL,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'sent', 'cancelled', 'failed')),
  sent_at TIMESTAMPTZ,
  sent_count INTEGER DEFAULT 0,
  error TEXT,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scheduled_notifications_status_time ON public.scheduled_notifications(status, scheduled_for);

-- -----------------------------------------------------------------------------
-- Backup snapshots (manual/auto backup log)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.backup_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  label TEXT,
  kind TEXT DEFAULT 'manual' CHECK (kind IN ('manual', 'auto')),
  status TEXT DEFAULT 'running' CHECK (status IN ('running', 'succeeded', 'failed')),
  storage_url TEXT,
  size_bytes BIGINT,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  error TEXT,
  created_by UUID REFERENCES public.profiles(id),
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_backup_snapshots_kind ON public.backup_snapshots(kind);

-- =============================================================================
-- Row Level Security
-- =============================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kyc ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kyc_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.savings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loan_qrs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loan_guarantors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rollovers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investment_pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investment_participations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loan_repayments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backup_snapshots ENABLE ROW LEVEL SECURITY;

-- Helper: check if current JWT is admin/staff
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role IN ('admin','superadmin','staff')
  )
$$;

-- Generic per-profile RLS (members can only see their own rows).
-- The service role bypasses RLS; the admin web uses the mobile backend with a
-- service-role token, so admin listings don't need dedicated policies here.
DO $$
DECLARE
  tbl TEXT;
  tables TEXT[] := ARRAY[
    'kyc','kyc_documents','savings','savings_goals','referrals',
    'wallets','transactions','bank_accounts','loans',
    'rollovers','investment_participations','notifications',
    'tickets','user_settings','watchlist'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', tbl || '_self_select', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', tbl || '_self_modify', tbl);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT USING (profile_id = auth.uid() OR public.is_staff())',
      tbl || '_self_select', tbl
    );
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL USING (profile_id = auth.uid() OR public.is_staff()) WITH CHECK (profile_id = auth.uid() OR public.is_staff())',
      tbl || '_self_modify', tbl
    );
  END LOOP;
END$$;

-- Custom RLS for loan_qrs (uses applicant_id)
DROP POLICY IF EXISTS loan_qrs_self_select ON public.loan_qrs;
DROP POLICY IF EXISTS loan_qrs_self_modify ON public.loan_qrs;
CREATE POLICY loan_qrs_self_select ON public.loan_qrs FOR SELECT USING (applicant_id = auth.uid() OR public.is_staff());
CREATE POLICY loan_qrs_self_modify ON public.loan_qrs FOR ALL USING (applicant_id = auth.uid() OR public.is_staff()) WITH CHECK (applicant_id = auth.uid() OR public.is_staff());

-- Custom RLS for loan_guarantors (uses guarantor_id)
DROP POLICY IF EXISTS loan_guarantors_self_select ON public.loan_guarantors;
DROP POLICY IF EXISTS loan_guarantors_self_modify ON public.loan_guarantors;
CREATE POLICY loan_guarantors_self_select ON public.loan_guarantors FOR SELECT USING (guarantor_id = auth.uid() OR public.is_staff());
CREATE POLICY loan_guarantors_self_modify ON public.loan_guarantors FOR ALL USING (guarantor_id = auth.uid() OR public.is_staff()) WITH CHECK (guarantor_id = auth.uid() OR public.is_staff());

-- Custom RLS for ticket_messages (uses author_id)
DROP POLICY IF EXISTS ticket_messages_self_select ON public.ticket_messages;
DROP POLICY IF EXISTS ticket_messages_self_modify ON public.ticket_messages;
CREATE POLICY ticket_messages_self_select ON public.ticket_messages FOR SELECT USING (author_id = auth.uid() OR public.is_staff());
CREATE POLICY ticket_messages_self_modify ON public.ticket_messages FOR ALL USING (author_id = auth.uid() OR public.is_staff()) WITH CHECK (author_id = auth.uid() OR public.is_staff());

-- Custom RLS for ticket_attachments (uses uploaded_by)
DROP POLICY IF EXISTS ticket_attachments_self_select ON public.ticket_attachments;
DROP POLICY IF EXISTS ticket_attachments_self_modify ON public.ticket_attachments;
CREATE POLICY ticket_attachments_self_select ON public.ticket_attachments FOR SELECT USING (uploaded_by = auth.uid() OR public.is_staff());
CREATE POLICY ticket_attachments_self_modify ON public.ticket_attachments FOR ALL USING (uploaded_by = auth.uid() OR public.is_staff()) WITH CHECK (uploaded_by = auth.uid() OR public.is_staff());

-- Custom RLS for ticket_status_history (uses changed_by)
DROP POLICY IF EXISTS ticket_status_history_self_select ON public.ticket_status_history;
DROP POLICY IF EXISTS ticket_status_history_self_modify ON public.ticket_status_history;
CREATE POLICY ticket_status_history_self_select ON public.ticket_status_history FOR SELECT USING (changed_by = auth.uid() OR public.is_staff());
CREATE POLICY ticket_status_history_self_modify ON public.ticket_status_history FOR ALL USING (changed_by = auth.uid() OR public.is_staff()) WITH CHECK (changed_by = auth.uid() OR public.is_staff());

-- Profiles, referral_events, investment_pools, audit_logs, system_settings
-- have their own custom policies:
DROP POLICY IF EXISTS profiles_public_select ON public.profiles;
CREATE POLICY profiles_public_select ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS profiles_self_insert ON public.profiles;
CREATE POLICY profiles_self_insert ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS profiles_self_update ON public.profiles;
CREATE POLICY profiles_self_update ON public.profiles FOR UPDATE USING (auth.uid() = id OR public.is_staff());

DROP POLICY IF EXISTS referral_events_read ON public.referral_events;
CREATE POLICY referral_events_read ON public.referral_events FOR SELECT
  USING (referrer_id = auth.uid() OR referred_id = auth.uid() OR public.is_staff());
DROP POLICY IF EXISTS referral_events_write ON public.referral_events;
CREATE POLICY referral_events_write ON public.referral_events FOR ALL
  USING (referrer_id = auth.uid() OR public.is_staff())
  WITH CHECK (referrer_id = auth.uid() OR public.is_staff());

DROP POLICY IF EXISTS investment_pools_read ON public.investment_pools;
CREATE POLICY investment_pools_read ON public.investment_pools FOR SELECT USING (true);
DROP POLICY IF EXISTS investment_pools_write ON public.investment_pools;
CREATE POLICY investment_pools_write ON public.investment_pools FOR ALL USING (public.is_staff());

DROP POLICY IF EXISTS audit_logs_read ON public.audit_logs;
CREATE POLICY audit_logs_read ON public.audit_logs FOR SELECT USING (actor_id = auth.uid() OR public.is_staff());
DROP POLICY IF EXISTS audit_logs_insert ON public.audit_logs;
CREATE POLICY audit_logs_insert ON public.audit_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS system_settings_read ON public.system_settings;
CREATE POLICY system_settings_read ON public.system_settings FOR SELECT USING (true);
DROP POLICY IF EXISTS system_settings_write ON public.system_settings;
CREATE POLICY system_settings_write ON public.system_settings FOR ALL USING (public.is_staff());

-- -----------------------------------------------------------------------------
-- Trigger: auto-create dependent rows when a new auth user signs up
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, user_id, email, name, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'userId', 'USR-' || substr(NEW.id::text, 1, 8)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'role', 'member')
  )
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.wallets (profile_id)
  VALUES (NEW.id)
  ON CONFLICT (profile_id) DO NOTHING;

  INSERT INTO public.savings (profile_id)
  VALUES (NEW.id)
  ON CONFLICT (profile_id) DO NOTHING;

  INSERT INTO public.user_settings (profile_id)
  VALUES (NEW.id)
  ON CONFLICT (profile_id) DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Convenience: auto-updated_at
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  tbl TEXT;
  tables TEXT[] := ARRAY[
    'profiles','kyc','savings','savings_goals','referrals','referral_events',
    'wallets','transactions','bank_accounts','loans','loan_qrs','loan_guarantors',
    'rollovers','investment_pools','investment_participations','notifications',
    'tickets','ticket_messages','user_settings','loan_repayments',
    'scheduled_notifications'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_updated_at ON public.%I', tbl);
    EXECUTE format(
      'CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.%I
       FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()',
      tbl
    );
  END LOOP;
END$$;
