import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:coopvest_mobile/presentation/providers/auth_provider.dart';
import 'package:coopvest_mobile/data/repositories/auth_repository.dart';
import 'package:coopvest_mobile/core/network/api_client.dart';
import 'package:coopvest_mobile/data/models/auth_models.dart';

@GenerateMocks([AuthRepository, ApiClient])
void main() {
  late AuthNotifier authNotifier;
  late MockAuthRepository mockAuthRepository;
  late MockApiClient mockApiClient;

  setUp(() {
    mockAuthRepository = MockAuthRepository();
    mockApiClient = MockApiClient();
    authNotifier = AuthNotifier(mockAuthRepository, mockApiClient);
  });

  group('AuthNotifier Tests', () {
    test('Initial state is unauthenticated', () {
      expect(authNotifier.state.status, AuthStatus.unauthenticated);
    });

    test('Login success updates state to authenticated', () async {
      final user = User(
        id: '1',
        email: 'test@example.com',
        firstName: 'Test',
        lastName: 'User',
        phone: '08012345678',
        isEmailVerified: true,
        isKycVerified: true,
        createdAt: DateTime.now(),
      );
      
      final authResponse = AuthResponse(
        user: user,
        accessToken: 'access_token',
        refreshToken: 'refresh_token',
      );

      when(mockAuthRepository.login(
        email: 'test@example.com',
        password: 'password123',
      )).thenAnswer((_) async => authResponse);

      await authNotifier.login(
        email: 'test@example.com',
        password: 'password123',
      );

      expect(authNotifier.state.status, AuthStatus.authenticated);
      expect(authNotifier.state.user, user);
      verify(mockApiClient.setAuthToken('access_token')).called(1);
    });

    test('Logout clears state and tokens', () async {
      await authNotifier.logout();

      expect(authNotifier.state.status, AuthStatus.unauthenticated);
      expect(authNotifier.state.user, null);
      verify(mockAuthRepository.logout()).called(1);
      verify(mockApiClient.clearAuthToken()).called(1);
    });
  });
}

// Mock classes (usually generated by build_runner, but defined here for simplicity in this context)
class MockAuthRepository extends Mock implements AuthRepository {
  @override
  Future<AuthResponse> login({required String email, required String password, String? deviceId}) =>
      super.noSuchMethod(
        Invocation.method(#login, [], {#email: email, #password: password, #deviceId: deviceId}),
        returnValue: Future.value(AuthResponse(
          user: User(id: '1', email: '', firstName: '', lastName: '', phone: '', isEmailVerified: true, isKycVerified: true, createdAt: DateTime.now()),
          accessToken: '',
          refreshToken: '',
        )),
      );

  @override
  Future<void> logout() => super.noSuchMethod(
        Invocation.method(#logout, []),
        returnValue: Future.value(),
      );
}

class MockApiClient extends Mock implements ApiClient {
  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(#setAuthToken, [token]),
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(#clearAuthToken, []),
      );
}
